### ISSUE TITLE
newlines not removed in plain_extract

### ISSUE THREAD

**Issue by tallemeersch** [qurator-spk/dinglehopper#107]
In ocr_files.py, line 170, readlines is performed. This method keeps the newlines, leading to incorrect CER score. Below is the current report given ground truth as txt and OCR as XML vs. the report when strip() is added to lines 170, i.e. make_segment(no, line.strip())

![image](https://github.com/qurator-spk/dinglehopper/assets/37655335/f2558cf9-2066-4d9e-a3e7-e306f6afebbc)

![image](https://github.com/qurator-spk/dinglehopper/assets/37655335/1ab3d413-acd7-4277-b6be-010bf8614def)

**Comment by mikegerber** [comment]
Thanks @tallemeersch! Could you upload the two files, I suspect there is an issue with the line endings (and I'm always interested in real user data)?

**Comment by mikegerber** [comment]
Nevermind, I believe this always happens. I'll look into it.

**Comment by tallemeersch** [comment]
Hereby the files attached. The command to produce the report was:
dinglehopper --textequiv-level line 02_GT.txt 02.xml
[02.zip](https://github.com/qurator-spk/dinglehopper/files/15133083/02.zip)

**Comment by mikegerber** [comment]
![grafik](https://github.com/qurator-spk/dinglehopper/assets/34309482/a6a33bf0-8c24-49b8-8106-a7d6ae8fee6c)

Fix is in git master and will be in the next release!

**Comment by tallemeersch** [comment]
Thanks!
