### ISSUE TITLE
Extend json report to allow evaluation of a series of pages

### ISSUE THREAD

**Issue by VolkerHartmann** [qurator-spk/dinglehopper#14]
To analyze a series of pages as a whole, it would be helpful to include the number of characters/words in the created json file.
e.g.: noOfCharacters=200
        noOfWords=43

**Comment by mikegerber** [comment]
Since https://github.com/qurator-spk/dinglehopper/commit/745095e52c17aa9e07ded01a671f3906b04830b2 dinglehopper now includes the number of characters and words in the JSON report.

Example report:
~~~json
{
    "gt": "test-gt.page2018.xml",
    "ocr": "test-fake-ocr.page2018.xml",
    "cer": 0.0024183796856106408,
    "wer": 0.015384615384615385,
    "n_characters": 827,
    "n_words": 130
}
~~~

**Comment by mikegerber** [comment]
Side note: This allows generating a per-workspace (= per-document) CER by calculating `CER_total = sum(CER_x*n_x)/sum(n_x)`. I would even include such a total CER in a OCR-Dy per-workspace report, but I am not sure how to save this in the workspace cleanly.

@kba: Ideas?

**Comment by kba** [comment]
```sh
ocrd workspace add -G EVAL_DINGLEHOPPER -i dinglehopper-`date -I` -m application/json report.json
```
?

**Comment by mikegerber** [comment]
> ```shell
> ocrd workspace add -G EVAL_DINGLEHOPPER -i dinglehopper-`date -I` -m application/json report.json
> ```

I was under the impression that files in file groups must relate to pages (not the document)?

**Comment by kba** [comment]
> I was under the impression that files in file groups must relate to pages (not the document)?

They should but I see no other option to store persistently. A workspace is just a more user-friendly interface to the METS.

If it was an OCRD-ZIP, we could store such info in the `metadata/` directory.
