### ISSUE TITLE
Feature Request: Comparison options

### ISSUE THREAD

**Issue by jbarth-ubhd** [qurator-spk/dinglehopper#25]
It would be nice to have an option to ...
 * fold accented and uppercase characters to lowercase (Ä → a) and to ignore punctation. 
 * let dinglehopper try to arrange paragraphs so that wrong segmentation order (perhaps not so important for full text search) can be ignored

**Comment by mikegerber** [comment]
These are three things, could you open separate issues for this? I'll definitely consider all of them.
