### ISSUE TITLE
Add naming parameter for output file

### ISSUE THREAD

**Issue by GrazingScientist** [qurator-spk/dinglehopper#27]
There should be a way to parameterize the name of the output file.

If I evaluate multiple files, with the `dinglehopper` command, it should be possible to name every output file. Currently, I have to run a script that renames each `report.json` or `report.html`.

**Comment by mikegerber** [comment]
Agreed! This should be easy to do.

**Comment by mikegerber** [comment]
It's actually already there, `REPORT_PREFIX` in the README:

```
Usage: dinglehopper [OPTIONS] GT OCR [REPORT_PREFIX]
```

I'll update the help text and README with more info.
