### ISSUE TITLE
Add --progress parameter

### ISSUE THREAD

**Issue by GrazingScientist** [qurator-spk/dinglehopper#30]
Please provide a --verbose parameter. I just ran a comparison of a text file with an XML file (both not part of any OCR-D process) and waited forever. Finally, I aborted the process. It would be nice to know what was the issue internally....

In #26 a progress bar was proposed by @mikegerber .

**Comment by mikegerber** [comment]
Could you provide the data please?

The issue is probably that the run time of the comparison is O(mn) (~ quadratic), but I want to see if there is maybe another problem.

**Comment by mikegerber** [comment]
As of 5ed184c, there is now a `--progress` option in the normal CLI.
