### ISSUE TITLE
Documentation: README completeness, debug ocrd-tool.json

### ISSUE THREAD

**Issue by tboenig** [qurator-spk/dinglehopper#4]
Please debug your ocrd_tool.json file. 
I found  an error:  
```xml
<report valid="false">
  <error>[] 'version' is a required property</error>
</report>
```
You can find the ocrd-tool.json documentation: https://ocr-d.github.io/ocrd_tool

Please check your README file and complet them. Your README is fine but look at your file and compare your's with the ideal README file.
 ```
# Name of application


## Introduction
...

## Installation
...

## Usage
...

## Testing
...
```
Thank you very much.

**Comment by mikegerber** [comment]
Thanks! I've added installation and testing instructions in 1206c9b. As for the missing version number: This is intended as there is no version yet. It will be added as soon as we release an official version.
