### ISSUE TITLE
try cutting corners to become faster

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/dinglehopper#44]
I know the task of aligning concatenated pages is much harder than just aligning text lines from the same segmentation (as in `ocrd-cor-asv-ann-evaluate`). But here it's all the more pressing to get decent performance IMO.

Therefore I would suggest the following:

1. replace the matrix calculation with some C library backend (there are many existing packages for Python that already do this). The algorithm will still be _`O(n²)`_ but the linear factor will be an order of magnitude smaller IIRC.

2. Instead of aligning the full page, try to cut corners by making the problem _`n`_ smaller: first compare pairs of regions, taking the best fit, then compare pairs of lines, taking the best fit. This comparison above the line level could also be merely approximate (you only need a proportional score, no actual alignment, and you can have boundaries, no exhaustive search). For example, `difflib.SequenceMatcher.quick_ratio` can do this.

**Comment by mikegerber** [comment]
>     2. Instead of aligning the full page, try to cut corners by making the problem _`n`_ smaller: first compare pairs of regions, taking the best fit, then compare pairs of lines, taking the best fit. This comparison above the line level could also be merely approximate (you only need a proportional score, no actual alignment, and you can have boundaries, no exhaustive search). For example, `difflib.SequenceMatcher.quick_ratio` can do this.

The one thing that made me start this project is that the other evaluation tools were terrible to audit. I will not "cut corners" if that makes the evaluation/evaluation code hard to understand or even incorrect.

**Comment by bertsky** [comment]
> The one thing that made me start this project is that the other evaluation tools were terrible to audit. I will not "cut corners" if that makes the evaluation/evaluation code hard to understand or even incorrect.

Frankly, I don't comprehend that response. What does choosing an efficient backend or making better algorithmic choices have to do with code quality?
