### ISSUE TITLE
No tests are run for PRs?

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#68]
#67 caused the code to fail, and the tests weren't run for the PR. Why?

**Comment by kba** [comment]
> #67 caused the code to fail, and the tests weren't run for the PR. Why?

Pull requests from branches in other remotes are not tested in Circle CI by default for security reasons (they could extract secrets like passwords and tokens). You have to enable "Build forked pull requests" in the settings.

**Comment by mikegerber** [comment]
> > #67 caused the code to fail, and the tests weren't run for the PR. Why?
> 
> Pull requests from branches in other remotes are not tested in Circle CI by default for security reasons (they could extract secrets like passwords and tokens). You have to enable "Build forked pull requests" in the settings.

Thanks! I'll need to think about this.

**Comment by mikegerber** [comment]
Fixed in #96. 

Needs more review for security: I checked the security guides and updated some settings but with this stuff it's best to look twice.
