### ISSUE TITLE
Update RapidFuzz again

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#69]
For now, we stick to rapidfuzz ~ 2.0.0, because later rapidfuzz seems to produce un-slice-able editops (see #67). I've reverted #67 for now, but, when fixed, the changes needs to be merged again.

**Comment by maxbachmann** [comment]
Hm, I never added the slicing feature when creating my own Editops class. I can add slicing to the Editops class.
Right now there are two workarounds for your slicing:
convert to list which is essentially what was done in the old API
```python
>>> ops.as_list()[1:]
```
modify in place:
```
del ops[0]
```

**Comment by maxbachmann** [comment]
since you use
```python
ops = ops[1:]
```
I would use
```python
del ops[0]
```
since it avoids creating a copy of the container

**Comment by mikegerber** [comment]
> I would use
> 
> ```python
> del ops[0]
> ```
> 
> since it avoids creating a copy of the container

Good idea, I'll change it.

**Comment by mikegerber** [comment]
c4e85da5aba03e7b0a71f6b4af972a7d8430f56a fixes this, the remaining problem is currently not of relevance for the normal operation of dinglehopper I think.
