### ISSUE TITLE
DingleHopper does not create results

### ISSUE THREAD

**Issue by stefanCCS** [qurator-spk/dinglehopper#71]
Using `ocrd, version 2.38.0`

I have tried out ocrd-dinglehopper like this:
```
ocrd-dinglehopper -l DEBUG -I $gtfileGrp,$ocrFileGrp -O $dinglefolder -P textequiv_level line
```
Somehow, from one of the input files no text is  taken:
![image](https://user-images.githubusercontent.com/61045115/186677718-df59a898-533e-445c-aea2-3d299d1f70eb.png)
```
{
    "gt": "OCR-D-SEG-KRAK/OCR-D-SEG-KRAK_4749_007817786_00157.xml",
    "ocr": "OCR-D-TESS-OCR-MOD-04/OCR-D-TESS-OCR-MOD-04-4749_007817786_00157.xml",

    "cer": 4.5,
    "wer": Infinity,

    "n_characters": 56,
    "n_words": 0
}
```

Any  idea?

**Comment by kba** [comment]
Can you provide the GT and OCR for this file as PAGE-XML? Looks to me like the OCR only recognized `.` for every character?

**Comment by stefanCCS** [comment]
Well, this was hint enough - many thanks.
My GT-PAGE does not contain any text (I do not know at this moment ...). Therefore, DingleHopper just shows, what is available.
I will close this issue now.
