### ISSUE TITLE
Installing is broken in current master

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#77]
Due to confusion with pyenv etc. I am not sure and need to check again.

May be related to #76.

**Comment by mikegerber** [comment]
Yeah it's broken, and I didn't notice because it is
- **NOT** broken when installing with `pip install -e .` and testing in the dinglehopper source directory
- broken when installing with `pip install .`

Great joy.

**Comment by mikegerber** [comment]
👀 @bertsky 

There was some confusion, I thought it was fixed, etc. etc.

**Comment by bertsky** [comment]
> There was some confusion, I thought it was fixed, etc. etc.

Yes, still [broken](https://github.com/OCR-D/ocrd_all/pull/356#issuecomment-1474492390) AFAIK. (For example, @kba just re-instated that version on ocrd_all, and voila it [broke the CI again](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/889/workflows/dfb55c1a-515d-4872-abf3-569e17271aa8/jobs/1142).

**Comment by mikegerber** [comment]
> > There was some confusion, I thought it was fixed, etc. etc.
> 
> Yes, still [broken](https://github.com/OCR-D/ocrd_all/pull/356#issuecomment-1474492390) AFAIK. (For example, @kba just re-instated that version on ocrd_all, and voila it [broke the CI again](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/889/workflows/dfb55c1a-515d-4872-abf3-569e17271aa8/jobs/1142).

Yeah I know now (since Friday) and will fix it today

**Comment by mikegerber** [comment]
@kba I'm probably "over-communicating" but just to came sure: I *thought* the remaining issue is eynollah having the old style namespace but that's another, second problem.

**Comment by kba** [comment]
> @kba I'm probably "over-communicating" but just to make sure: I _thought_ the remaining issue is eynollah having the old style namespace but that's another, second problem.

Over-communicating is just fine :-) We should fix all the qurator namespace changes in one fell swoop, test them and create a new release of ocrd_all then. For now, the latest ocrd_all release contains dinglehopper in the commit just before the namespace change.

**Comment by mikegerber** [comment]
Note to self: In this case, testing the install in a *fresh* virtualenv also was necessary.

**Comment by bertsky** [comment]
> We should fix all the qurator namespace changes in one fell swoop, test them and create a new release of ocrd_all then.

Is it really inevitable to change namespace pkg implementation? Is there no other way around the deprecation warning?

I am pretty sure this will fall on our feet again and again, because installations will _not_ be equally "swooped" to the new versions likewise. (And we cannot even solve this via version requirements, because none of the qurator packages depend on each other.)

**Comment by mikegerber** [comment]
I have a fix ready ([calling find_namespace_packages is necessary](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages)) but I can't push currently due to [GitHub's problems](https://www.githubstatus.com).

**Comment by mikegerber** [comment]
I have a fix ready ([calling find_namespace_packages is necessary](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages)) but I can't push currently due to [GitHub's problems](https://www.githubstatus.com).

**Comment by kba** [comment]
> I am pretty sure this will fall on our feet again and again, because installations will not be equally "swooped" to the new versions likewise. (And we cannot even solve this via version requirements, because none of the qurator packages depend on each other.)

The decision is up to @qurator-spk/dev, I only noticed the deprecation warning. IIUC one of the reasonings for adapting this is that QURATOR project has ended, MMK project has begun and this would be part of the consolidation.

As for breaking installations: As long as people follow the upgrade instructions (deactivate/remove venv, `make all` for native; `docker pull ocrd/all` for docker) that should™️ not be a problem.

**Comment by mikegerber** [comment]
I've now removed the namespace prefix (`s/qurator.dinglehopper/dinglehopper` and associated changes) altogether.
